# syntax=docker/dockerfile:1
# Generated by hyperi-rustlib deployment module
# Base image: Ubuntu 24.04 TTS
#
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# Multi-arch: CI places pre-built binaries in dist/ as:
#   dist/dfe-receiver-{version}-linux-amd64
#   dist/dfe-receiver-{version}-linux-arm64
# TARGETARCH is set by docker buildx (amd64 or arm64).

FROM ubuntu:24.04

ARG TARGETARCH=amd64

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Copy the target-arch binary from CI dist/ — uses BuildKit bind mount
# so dist/ is not included in any image layer.
RUN --mount=type=bind,source=dist,target=/dist \
    binary=$(find /dist -name "dfe-receiver-*-linux-${TARGETARCH}" | head -1) && \
    [ -f "$binary" ] || { echo "Binary not found for TARGETARCH=${TARGETARCH}"; exit 1; } && \
    cp "$binary" /usr/local/bin/dfe-receiver && \
    chmod +x /usr/local/bin/dfe-receiver

RUN useradd --create-home --uid 10001 appuser
USER appuser

EXPOSE 9090 8080 6000 4317 4318 5044 8088

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-receiver"]
CMD ["--config", "/etc/dfe-receiver/config.yaml"]
