# Project:   dfe-receiver
# File:      Dockerfile
# Purpose:   production container image
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# AUTOGENERATED -- do not edit by hand.
# Generated by scalo::deployment::generate_dockerfile()
# Schema version: 4
# Source contract: dfe-receiver::deployment::contract()
# Regenerate by calling scalo::deployment::generate_dockerfile() on that contract.

FROM debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a

LABEL io.hyperi.profile="production"

# Runtime shared libraries for dynamically-linked Rust crates.
# Apt versions are unpinned because Debian drops superseded ones, so the digest-pinned base is what fixes the release.
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping gnupg \
    && curl -fsSL https://packages.confluent.io/clients/deb/archive.key -o /tmp/repo-key.asc \
    && gpg --show-keys --with-colons --with-fingerprint /tmp/repo-key.asc \
       > /tmp/repo-key.info \
    && grep -q "^fpr:::::::::CBBB821E8FAF364F79835C438B1DA6120C2BF624:" /tmp/repo-key.info \
    && rm -f /tmp/repo-key.info \
    && gpg --dearmor -o /usr/share/keyrings/confluent-clients.gpg /tmp/repo-key.asc \
    && rm -f /tmp/repo-key.asc \
    && echo "deb [signed-by=/usr/share/keyrings/confluent-clients.gpg] \
       https://packages.confluent.io/clients/deb bookworm main" \
       > /etc/apt/sources.list.d/confluent-clients.list \
    && apt-get update && apt-get install -y --no-install-recommends \
       librdkafka1 libssl3t64 zlib1g libzstd1 \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-receiver /usr/local/bin/dfe-receiver
RUN chmod +x /usr/local/bin/dfe-receiver

# Ubuntu 24.04 ships with ubuntu user at UID 1000 -- remove before creating appuser
RUN if id ubuntu >/dev/null 2>&1; then userdel -r ubuntu; fi && useradd --create-home --uid 1000 appuser
# Numeric, so Kubernetes runAsNonRoot can verify it without reading /etc/passwd.
USER 1000

EXPOSE 9090 8080
# Conditional listeners, not EXPOSEd -- publish explicitly when enabled:
#   6000/tcp grpc -- when config.grpc.enabled is "true"
#   4317/tcp otlp-grpc -- when config.otlp.enabled is "true"
#   4318/tcp otlp-http -- when config.otlp.enabled is "true"
#   5044/tcp beats -- when config.lumberjack.enabled is "true"
#   8088/tcp hec -- when config.splunk_hec.enabled is "true"
#   9091/tcp prometheus-rw -- when config.prometheus_rw.enabled is "true"
#   8090/tcp webhook -- when config.webhook.enabled is "true"
#   514/tcp syslog -- when config.syslog.enabled is "true"
#   514/udp syslog-udp -- when config.syslog.enabled is "true"
#   6514/tcp syslog-tls -- when config.syslog.enabled is "true"
#   24224/tcp fluent -- when config.fluent.enabled is "true"
#   12201/tcp gelf -- when config.gelf.enabled is "true"
#   2055/udp netflow -- when config.flow.enabled is "true"
#   4739/udp netflow-ipfix -- when config.flow.enabled is "true"
#   6343/udp sflow -- when config.flow.enabled is "true"

# Shell form maps any curl failure to exit 1, the only unhealthy status Docker defines.
# hadolint ignore=DL3025
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/livez > /dev/null || exit 1

ENTRYPOINT ["dfe-receiver"]
CMD ["--config", "/etc/dfe-receiver/config.yaml"]
