# Project:   dfe-receiver
# File:      Dockerfile
# Purpose:   production container image
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# AUTOGENERATED -- do not edit by hand.
# Generated by scalo::deployment::generate_dockerfile()
# Schema version: 2
# Source contract: dfe-receiver::deployment::contract()
# Regenerate with: `dfe-receiver emit-dockerfile > Dockerfile`

FROM debian:trixie-slim

LABEL io.hyperi.profile="production"

# Runtime shared libraries for dynamically-linked Rust crates.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping gnupg \
    && curl -fsSL https://packages.confluent.io/clients/deb/archive.key \
       | gpg --dearmor -o /usr/share/keyrings/confluent-clients.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/confluent-clients.gpg] \
       https://packages.confluent.io/clients/deb bookworm main" \
       > /etc/apt/sources.list.d/confluent-clients.list \
    && apt-get update && apt-get install -y --no-install-recommends \
       librdkafka1 libssl3 zlib1g libzstd1 \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-receiver /usr/local/bin/dfe-receiver
RUN chmod +x /usr/local/bin/dfe-receiver

# Ubuntu 24.04 ships with ubuntu user at UID 1000 -- remove before creating appuser
RUN if id ubuntu >/dev/null 2>&1; then userdel -r ubuntu; fi && useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 9090 8080 6000 4317 4318 5044 8088 9091 514 6514 24224 12201 2055 4739 6343

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/health/live > /dev/null || exit 1

ENTRYPOINT ["dfe-receiver"]
CMD ["--config", "/etc/dfe-receiver/config.yaml"]
