{{- if not .Values.kafka.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-receiver.kafkaSecretName" . }}
  labels:
    {{- include "dfe-receiver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kafka.secretKeys.username }}: {{ .Values.kafka.username | b64enc | quote }}
  {{ .Values.kafka.secretKeys.password }}: {{ .Values.kafka.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-receiver.authSecretName" . }}
  labels:
    {{- include "dfe-receiver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secretKeys.bearer-tokens }}: {{ .Values.auth.bearer-tokens | b64enc | quote }}
{{- end }}
