apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfe-receiver.fullname" . }}
  labels:
    {{- include "dfe-receiver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: grpc
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: beats
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: hec
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: prometheus-rw
    - port: 514
      targetPort: 514
      protocol: TCP
      name: syslog
    - port: 6514
      targetPort: 6514
      protocol: TCP
      name: syslog-tls
    - port: 24224
      targetPort: 24224
      protocol: TCP
      name: fluent
    - port: 12201
      targetPort: 12201
      protocol: TCP
      name: gelf
    - port: 2055
      targetPort: 2055
      protocol: UDP
      name: netflow
    - port: 4739
      targetPort: 4739
      protocol: UDP
      name: netflow-ipfix
    - port: 6343
      targetPort: 6343
      protocol: UDP
      name: sflow
  selector:
    {{- include "dfe-receiver.selectorLabels" . | nindent 4 }}
