# Project:   dfe-receiver
# File:      .cargo/config.toml
# Purpose:   Cargo registry configuration
# License:   FSL-1.1-ALv2
# Copyright: (c) 2026 HYPERI PTY LIMITED

[registry]
global-credential-providers = ["cargo:token"]

[registries.hypersec]
index = "sparse+https://hypersec.jfrog.io/artifactory/api/cargo/hypersec-cargo-virtual/index/"
