// Vendored from prometheus/prometheus prompb/types.proto
// Stripped of gogoproto annotations for prost compatibility.
//
// Copyright 2017 Prometheus Team
// Licensed under the Apache License, Version 2.0

syntax = "proto3";
package prometheus;

message MetricMetadata {
  enum MetricType {
    UNKNOWN        = 0;
    COUNTER        = 1;
    GAUGE          = 2;
    HISTOGRAM      = 3;
    GAUGEHISTOGRAM = 4;
    SUMMARY        = 5;
    INFO           = 6;
    STATESET       = 7;
  }

  MetricType type = 1;
  string metric_family_name = 2;
  string help = 4;
  string unit = 5;
}

message Sample {
  double value    = 1;
  int64 timestamp = 2;  // milliseconds since Unix epoch
}

message Exemplar {
  repeated Label labels = 1;
  double value = 2;
  int64 timestamp = 3;  // milliseconds since Unix epoch
}

message Histogram {
  enum ResetHint {
    UNKNOWN = 0;
    YES     = 1;
    NO      = 2;
    GAUGE   = 3;
  }

  oneof count {
    uint64 count_int   = 1;
    double count_float = 2;
  }
  double sum = 3;
  sint32 schema             = 4;
  double zero_threshold     = 5;
  oneof zero_count {
    uint64 zero_count_int     = 6;
    double zero_count_float   = 7;
  }

  repeated BucketSpan negative_spans =  8;
  repeated sint64 negative_deltas    =  9;
  repeated double negative_counts    = 10;

  repeated BucketSpan positive_spans = 11;
  repeated sint64 positive_deltas    = 12;
  repeated double positive_counts    = 13;

  ResetHint reset_hint               = 14;
  int64 timestamp = 15;  // milliseconds since Unix epoch

  repeated double custom_values = 16;
}

message BucketSpan {
  sint32 offset = 1;
  uint32 length = 2;
}

message TimeSeries {
  repeated Label labels         = 1;
  repeated Sample samples       = 2;
  repeated Exemplar exemplars   = 3;
  repeated Histogram histograms = 4;
}

message Label {
  string name  = 1;
  string value = 2;
}

message Labels {
  repeated Label labels = 1;
}
